-- MySQL Script generated by MySQL Workbench
-- Mon Dec  6 23:47:37 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema orm_exo
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema orm_exo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `orm_exo` DEFAULT CHARACTER SET utf8 ;
USE `orm_exo` ;

-- -----------------------------------------------------
-- Table `orm_exo`.`service`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `orm_exo`.`service` (
  `idservice` INT NOT NULL AUTO_INCREMENT,
  `libelle` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idservice`),
  UNIQUE INDEX `idservice_UNIQUE` (`idservice` ASC) ,
  UNIQUE INDEX `libelle_UNIQUE` (`libelle` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `orm_exo`.`state`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `orm_exo`.`state` (
  `idstate` INT NOT NULL AUTO_INCREMENT,
  `libelle` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idstate`),
  UNIQUE INDEX `libelle_UNIQUE` (`libelle` ASC) ,
  UNIQUE INDEX `idstate_UNIQUE` (`idstate` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `orm_exo`.`ticket`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `orm_exo`.`ticket` (
  `idticket` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL,
  `description` TEXT NOT NULL,
  `date` DATETIME NOT NULL,
  `service_idservice` INT NOT NULL,
  `state_idstate` INT NOT NULL,
  PRIMARY KEY (`idticket`),
  UNIQUE INDEX `idticket_UNIQUE` (`idticket` ASC) ,
  INDEX `fk_ticket_service_idx` (`service_idservice` ASC) ,
  INDEX `fk_ticket_state1_idx` (`state_idstate` ASC) ,
  CONSTRAINT `fk_ticket_service`
    FOREIGN KEY (`service_idservice`)
    REFERENCES `orm_exo`.`service` (`idservice`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ticket_state1`
    FOREIGN KEY (`state_idstate`)
    REFERENCES `orm_exo`.`state` (`idstate`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `orm_exo`.`comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `orm_exo`.`comment` (
  `idcomment` INT NOT NULL AUTO_INCREMENT,
  `texte` TEXT NOT NULL,
  `date` DATETIME NOT NULL,
  `ticket_idticket` INT NOT NULL,
  PRIMARY KEY (`idcomment`),
  UNIQUE INDEX `idcomment_UNIQUE` (`idcomment` ASC) ,
  INDEX `fk_comment_ticket1_idx` (`ticket_idticket` ASC) ,
  CONSTRAINT `fk_comment_ticket1`
    FOREIGN KEY (`ticket_idticket`)
    REFERENCES `orm_exo`.`ticket` (`idticket`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
